project:
  type: website

website:
  title: "Além da Média"
  description: "Blog do cientista de dados Bruno Pinheiro de Oliveira"
  navbar:
    right:
      - text: Sobre
        href: about.qmd
      - icon: github
        href: https://github.com/bruno-po
      - icon: linkedin
        href: https://linkedin.com/in/brunopinheirooliveira
    cookie-consent: true

format:
  html:
    theme: litera
    css: styles.css

editor: visual

